apiVersion: 1
datasources:
  - name: TimescaleDB
    type: postgres
    url: timescaledb:5432
    database: txgen
    user: txgen
    secureJsonData:
      password: txgen
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
